### ISSUE TITLE
Forked repositories don't use the correct GitHub token secret

### ISSUE THREAD

**Issue by sc0ttkclark** [rtCamp/action-phpcs-code-review#12]
When a forked repository runs the review for a PR back to the main repo, it does not utilize the main repo's secret (says the secret is not set).

See: https://github.com/pods-framework/pods/pull/5495

https://github.com/pods-framework/pods/pull/5495/checks?check_run_id=250675264

`[ERROR] Secret `GH_BOT_TOKEN` is missing. Please add it to this action for proper execution.`

**Comment by mrrobot47** [comment]
Closing this as it is very similar to issue: #11. Will communicate about this issue and updates on issue: #11 itself.
