### ISSUE TITLE
Why not `GITHUB_SHA`

### ISSUE THREAD

**Issue by divyarajmasani** [rtCamp/action-phpcs-code-review#21]
At time for reasons unknown to me, `GITHUB_EVENT_PATH` return empty.

So when github provides `GITHUB_SHA` ( commit hash ) directly why are we trying to extract it from `GITHUB_EVENT_PATH`.

https://github.com/rtCamp/action-phpcs-code-review/blob/3b6a0da35e37e63777dc57ec56a5036cf0ee3d5a/main.sh#L5

**Comment by mrrobot47** [comment]
Closing as fixed in https://github.com/rtCamp/action-phpcs-code-review/issues/19

**Comment by mrrobot47** [comment]
Can not use `GITHUB_SHA` as that is different from the last commit in PR and vip-go-ci fails with due that commit id as well.

The solution then for commit id is this only: https://github.com/rtCamp/action-phpcs-code-review/blob/3b6a0da35e37e63777dc57ec56a5036cf0ee3d5a/main.sh#L5

This gives the exact last commit id of PR.

**Comment by divyarajmasani** [comment]
Recent action fail make me look up the action file, and also checked the default env variables available when the even/action triggers. There I read this for `GITHUB_SHA` - `The commit SHA that triggered the workflow.`

Hence if the last commit triggered the pull_request action then it should have the last commit. With this idea I created the issue to understand why we are not using that variable.
