### ISSUE TITLE
Improve recognition of custom rulesets

### ISSUE THREAD

**Issue by jrfnl** [rtCamp/action-phpcs-code-review#4]
PHPCS custom rulesets can have any of the below names. Based on the readme and a summary code review, this action only recognizes one of them. All four, however, should be recognized.

* `.phpcs.xml`
* `phpcs.xml` (already recognized)
* `.phpcs.xml.dist`
* `phpcs.xml.dist`

**Comment by mbtamuli** [comment]
If multiple files exists, how should the order be determined?

**Comment by PatelUtkarsh** [comment]
We can use this order as mentioned on docs: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file

>Note: If multiple default configuration files are found, PHP_CodeSniffer will select one using the following order: .phpcs.xml, phpcs.xml, .phpcs.xml.dist, phpcs.xml.dist

**Comment by jrfnl** [comment]
What @PatelUtkarsh said, i.e. the order in which I listed them ;-)

**Comment by PatelUtkarsh** [comment]
I didn't double check your order, my bad. @jrfnl
