### ISSUE TITLE
Add support for Vault

### ISSUE THREAD

**Issue by PatelUtkarsh** [rtCamp/action-phpcs-code-review#7]
If the organization uses this action on multiple projects then we will have to do one of the following:
1. Use the same token - store somewhere (shared 1password/vault?)
2. Create a new token for each repo.

https://github.com/rtCamp/action-deploy-wordpress already uses the vault.

Ref: https://www.vaultproject.io

**Comment by mrrobot47** [comment]
Closing in favor of following patch:

https://github.com/rtCamp/action-phpcs-code-review/commit/a90c91947106d29facf41fd6680911647e76489b
https://github.com/rtCamp/action-phpcs-code-review/commit/d0d5a15dd8c0f3c96cb06189935ba8bcac31ffb9
https://github.com/rtCamp/action-phpcs-code-review/commit/53508644288ba93885e3adf49808b9ac284c48a8
