### ISSUE TITLE
Use local phpcs.xml

### ISSUE THREAD

**Issue by obenland** [rtCamp/action-phpcs-code-review#9]
The docs mention
> If your git repo have a file named phpcs.xml in the root of the repository, then that will take precedence.

That does not seem to be the case.
See https://github.com/Automattic/starter-page-templates/pull/14 where we add a phpcs.xml file in the root of the repo, but [that doesn't get picked up](https://github.com/Automattic/starter-page-templates/runs/133010771). 

Do you have any advice?

**Comment by mrrobot47** [comment]
>but that doesn't get picked up.

What does not get picked up? Can you please elaborate on the issue that you are facing. 
What is your expectation? What did you define in `phpcs.xml` which is not getting respected?

**Comment by obenland** [comment]
The phpcs.xml in the root of our repository doesn't seem to get picked up.

I'd expect [this line](https://github.com/rtCamp/action-phpcs-code-review/blob/master/main.sh#L28) to read something like
```
phpcs_standard="--phpcs-standard=$GITHUB_WORKSPACE/$phpcsfile"
```

**Comment by mrrobot47** [comment]
It is the same file, please check [this line](https://github.com/rtCamp/action-phpcs-code-review/blob/204f2c12f063909ec81c9387bf933bfc86c5efdd/main.sh#L8). The `$GITHUB_WORKSPACE` files are copied to `$RTBOT_WORKSPACE`.
